config:
  user-seq: 1
  org-code: 0000000000
  client-id: Tb22zxBwrQ5Nyd6YxWHsAK3y40qiKNsk
  client-secret: WGuexnPo8RYD8B60cMvDVnTZpPfeOA5I
  callback-url: https://apidev.myfn.net/MyData/AuthCallback
  user-ci: NsoFzzUqcMfSseGcFVbkARcukDJtCfxt
  api-code: AU01
  fnguide-code: 2208191972
  app-scheme: https://apidev.myfn.net/MyData
server:
  port: 443
  ssl:
    enabled: true
    protocol: TLS
    enabled-protocols: TLSv1.3
    key-store: classpath:key.p12
    key-store-type: PKCS12
    key-store-password: 123456
    key-alias: System
#

