server:
  port: 8443 #SSL ??? ?? ??
  ssl:
    enabled: false
#    key-store: "sslcert.co.kr.jks" ?? "sslcert.co.kr.pfx" ??
#    key-store-type: ??? ?? ??? "JKS" ?? "PKCS12" ??
#    key-store-password: xxxxxxxx  # jks ?? pfx ??
#    key-alias: xxxxx.com # (???) Alias ? ??. CSR ?? ????? CN ?
#    trust-store: # (???) "sslcert.co.kr.jks" ?? "sslcert.co.kr.pfx" ??. CSR ?? ?????, ??/?? ??? ?? ??
#    trust-store-password: xxxxxxxx  # (???) jks ?? pfx ??
