server:
  port: 443
  ssl:
    enabled: true
    protocol: TLS
    enabled-protocols: TLSv1.3
    key-store: classpath:key.p12
    key-store-type: PKCS12
    key-store-password: 123456
    key-alias: System
#

